import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "cyber-cyan": "#00f5ff",
        "cyber-orange": "#f77f00",
        "panel": "rgba(10, 25, 41, 0.6)",
        "on-secondary-fixed-variant": "#024b73",
        "surface-container": "#002235",
        "surface-bright": "#133d56",
        "inverse-primary": "#954a00",
        "primary": "#ffb784",
        "error-container": "#93000a",
        "surface-container-highest": "#0c3851",
        "primary-container": "#f77f00",
        "on-surface-variant": "#dec1af",
        "tertiary-container": "#92a1b6",
        "on-primary": "#502500",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "background": "#001523",
        "secondary-container": "#024b73",
        "surface-container-lowest": "#00101c",
        "on-secondary-fixed": "#001d31",
        "tertiary": "#b9c8de",
        "surface-dim": "#001523",
        "outline-variant": "#574335",
        "primary-fixed-dim": "#ffb784",
        "on-primary-container": "#592a00",
        "on-secondary-container": "#86bae8",
        "surface-tint": "#ffb784",
        "on-tertiary-container": "#293849",
        "on-tertiary-fixed": "#0d1c2d",
        "secondary": "#98ccfa",
        "surface-variant": "#0c3851",
        "on-primary-fixed-variant": "#713700",
        "primary-fixed": "#ffdcc6",
        "surface-container-low": "#001e2f",
        "inverse-surface": "#cae6ff",
        "inverse-on-surface": "#05344d",
        "on-primary-fixed": "#301400",
        "on-error": "#690005",
        "outline": "#a68c7b",
        "on-tertiary": "#233143",
        "tertiary-fixed": "#d4e4fa",
        "on-surface": "#cae6ff",
        "surface": "#001523",
        "on-tertiary-fixed-variant": "#39485a",
        "surface-container-high": "#002d45",
        "secondary-fixed-dim": "#98ccfa",
        "on-background": "#cae6ff",
        "tertiary-fixed-dim": "#b9c8de",
        "secondary-fixed": "#cce5ff",
        "on-secondary": "#003351",
        "crimson-glow": "#D62828"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
      backgroundImage: {
        'grid-pattern': "radial-gradient(rgba(0, 245, 255, 0.1) 1px, transparent 1px)",
      }
    },
  },
  plugins: [],
};
export default config;
