import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#454747",
        "on-surface-variant": "#acabaa",
        "secondary-container": "#3a3b3f",
        "on-tertiary-fixed-variant": "#666668",
        "primary-fixed": "#e2e2e2",
        "surface-container-highest": "#252626",
        "secondary-dim": "#9d9da2",
        "on-tertiary-fixed": "#49494b",
        "on-error-container": "#ff9993",
        "on-secondary": "#1f2024",
        "surface-variant": "#252626",
        "outline-variant": "#484848",
        "on-secondary-fixed": "#3e3f43",
        "primary-dim": "#b8b9b9",
        "on-surface": "#e7e5e5",
        "tertiary": "#fbf8fb",
        "on-secondary-fixed-variant": "#5b5b60",
        "outline": "#767575",
        "on-tertiary-container": "#575658",
        "tertiary-dim": "#edeaec",
        "on-primary-fixed": "#3e4040",
        "surface-container-high": "#1f2020",
        "on-primary": "#3f4041",
        "error-dim": "#bb5551",
        "inverse-surface": "#fcf9f8",
        "primary": "#c6c6c7",
        "error": "#ee7d77",
        "secondary-fixed": "#e3e2e7",
        "surface-bright": "#2b2c2c",
        "primary-fixed-dim": "#d4d4d4",
        "on-error": "#490106",
        "error-container": "#7f2927",
        "tertiary-fixed-dim": "#e7e4e7",
        "on-primary-fixed-variant": "#5a5c5c",
        "tertiary-fixed": "#f5f3f5",
        "surface-container-low": "#131313",
        "surface": "#0e0e0e",
        "surface-container": "#191a1a",
        "inverse-primary": "#5e5f60",
        "background": "#0e0e0e",
        "secondary-fixed-dim": "#d5d4d9",
        "tertiary-container": "#edeaec",
        "on-secondary-container": "#bfbfc4",
        "on-tertiary": "#5f5f61",
        "surface-tint": "#c6c6c7",
        "surface-dim": "#0e0e0e",
        "secondary": "#9d9da2",
        "on-background": "#e7e5e5",
        "on-primary-container": "#d0d0d0",
        "surface-container-lowest": "#000000",
        "inverse-on-surface": "#565555"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
      backgroundImage: {
        'grid-pattern': "radial-gradient(rgba(0, 245, 255, 0.1) 1px, transparent 1px)",
      }
    },
  },
  plugins: [],
};
export default config;
