import os
from fpdf import FPDF
from datetime import datetime

class PRDPDF(FPDF):
    def __init__(self, filename, date_str):
        super().__init__()
        self.doc_filename = filename
        self.date_str = date_str

    def header(self):
        # Arial bold 15
        self.set_font('helvetica', 'B', 15)
        # Title
        self.cell(100, 10, 'PRD Evaluator', border=0, ln=0, align='L')
        # Date
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 10, f'Date: {self.date_str}', border=0, ln=1, align='R')
        
        # Document name
        self.set_font('helvetica', '', 10)
        self.cell(0, 8, f'Evaluated Document: {self.doc_filename}', border=0, ln=1, align='L')
        
        # Line break
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('helvetica', 'I', 8)
        # Page number
        self.cell(0, 10, f'Generated by PRD Evaluator - prdevaluator.com | Page {self.page_no()}/{{nb}}', 0, 0, 'C')

def generate_pdf_report(evaluation_data: dict, filename: str) -> bytes:
    """Generates a PDF report and returns it as bytes."""
    date_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    pdf = PRDPDF(filename=filename, date_str=date_str)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- HALAMAN 1: SUMMARY ---
    pdf.set_font('helvetica', 'B', 16)
    pdf.cell(0, 10, 'SUMMARY', ln=1)
    pdf.ln(5)

    result = evaluation_data.get("result_json", {})
    final_score = result.get("final_score", 0)
    verdict = result.get("verdict", "Unknown")

    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, f'FINAL SCORE: {final_score} / 10', border=1, ln=1, align='C', fill=False)
    pdf.cell(0, 10, f'VERDICT: {verdict}', border=1, ln=1, align='C', fill=False)
    pdf.ln(10)

    # Strengths and Weaknesses
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(90, 8, 'Strengths:', ln=0)
    pdf.cell(90, 8, 'Weaknesses:', ln=1)
    
    pdf.set_font('helvetica', '', 10)
    strengths = result.get("strengths", [])
    weaknesses = result.get("weaknesses", [])
    
    # Simple list print
    max_len = max(len(strengths), len(weaknesses))
    for i in range(max_len):
        s = f"• {strengths[i]}" if i < len(strengths) else ""
        w = f"• {weaknesses[i]}" if i < len(weaknesses) else ""
        # Handle long lines simply for MVP
        pdf.cell(90, 6, s[:45] + ("..." if len(s)>45 else ""), ln=0)
        pdf.cell(90, 6, w[:45] + ("..." if len(w)>45 else ""), ln=1)
    
    pdf.ln(10)


    # --- HALAMAN 2: DETAIL SCORES ---
    pdf.add_page()
    pdf.set_font('helvetica', 'B', 16)
    pdf.cell(0, 10, 'DETAIL SCORES', ln=1)
    pdf.ln(5)

    category_scores = result.get("category_scores", {})
    for cat, data in category_scores.items():
        score = data.get("score")
        if score is None:
            score_str = "N/A"
        else:
            score_str = f"{score}/10"

        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 8, f"Category: {cat.replace('_', ' ').title()}", ln=1)
        
        pdf.set_font('helvetica', '', 12)
        pdf.cell(0, 8, f"Score: {score_str}", ln=1)
        
        pdf.set_font('helvetica', 'I', 10)
        pdf.multi_cell(0, 6, f"Explanation: {data.get('explanation', '')}")
        pdf.multi_cell(0, 6, f"Evidence: \"{data.get('evidence', '')}\"")
        pdf.ln(5)

    # --- HALAMAN 3: RECOMMENDATIONS ---
    pdf.add_page()
    pdf.set_font('helvetica', 'B', 16)
    pdf.cell(0, 10, 'RECOMMENDATIONS', ln=1)
    pdf.ln(5)

    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, 'Missing Sections:', ln=1)
    pdf.set_font('helvetica', '', 10)
    
    missing = result.get("missing_sections", [])
    if not missing:
        pdf.cell(0, 6, "• None (All essential sections found)", ln=1)
    else:
        for m in missing:
            pdf.cell(0, 6, f"• {m}", ln=1)
            
    pdf.ln(5)

    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 8, 'Improvement Suggestions:', ln=1)
    pdf.set_font('helvetica', '', 10)
    suggs = result.get("improvement_suggestions", [])
    if not suggs:
        pdf.cell(0, 6, "• None", ln=1)
    else:
        for s in suggs:
            pdf.multi_cell(0, 6, f"• {s}")

    return pdf.output(dest='S')
