import os
from fpdf import FPDF
from datetime import datetime

# Sanitize text to replace problematic characters
def sanitize_text(text):
    """Clean text for safe PDF rendering."""
    if not isinstance(text, str):
        text = str(text)
    return text

class PRDPDF(FPDF):
    def __init__(self, filename, date_str):
        super().__init__()
        self.doc_filename = filename
        self.date_str = date_str
        
        # Add Unicode font - DejaVu is bundled with fpdf2
        self.add_font("DejaVu", "", "DejaVuSans.ttf", uni=True)
        self.add_font("DejaVu", "B", "DejaVuSans-Bold.ttf", uni=True)
        self.add_font("DejaVu", "I", "DejaVuSans-Oblique.ttf", uni=True)
        self.add_font("DejaVu", "BI", "DejaVuSans-BoldOblique.ttf", uni=True)

    def header(self):
        self.set_font('DejaVu', 'B', 15)
        self.cell(100, 10, 'PRD Evaluator', border=0, ln=0, align='L')
        self.set_font('DejaVu', 'I', 10)
        self.cell(0, 10, f'Date: {self.date_str}', border=0, ln=1, align='R')
        
        self.set_font('DejaVu', '', 10)
        self.cell(0, 8, f'Evaluated Document: {sanitize_text(self.doc_filename)}', border=0, ln=1, align='L')
        
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('DejaVu', 'I', 8)
        self.cell(0, 10, f'Generated by PRD Evaluator - prdevaluator.com | Page {self.page_no()}/{{nb}}', 0, 0, 'C')

def generate_pdf_report(evaluation_data: dict, filename: str) -> bytes:
    """Generates a PDF report and returns it as bytes."""
    date_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    pdf = PRDPDF(filename=filename, date_str=date_str)
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- PAGE 1: SUMMARY ---
    pdf.set_font('DejaVu', 'B', 16)
    pdf.cell(0, 10, 'SUMMARY', ln=1)
    pdf.ln(5)

    result = evaluation_data.get("result_json", {})
    if not isinstance(result, dict):
        result = {}
    final_score = result.get("final_score", 0)
    verdict = result.get("verdict", "Unknown")

    pdf.set_font('DejaVu', 'B', 14)
    pdf.cell(0, 10, f'FINAL SCORE: {final_score} / 10', border=1, ln=1, align='C', fill=False)
    pdf.cell(0, 10, f'VERDICT: {sanitize_text(verdict)}', border=1, ln=1, align='C', fill=False)
    pdf.ln(10)

    # Strengths and Weaknesses
    pdf.set_font('DejaVu', 'B', 12)
    pdf.cell(90, 8, 'Strengths:', ln=0)
    pdf.cell(90, 8, 'Weaknesses:', ln=1)
    
    pdf.set_font('DejaVu', '', 9)
    strengths = result.get("strengths", [])
    weaknesses = result.get("weaknesses", [])
    if not isinstance(strengths, list):
        strengths = []
    if not isinstance(weaknesses, list):
        weaknesses = []
    
    max_len = max(len(strengths), len(weaknesses), 1)
    for i in range(max_len):
        s = f"- {sanitize_text(strengths[i])}" if i < len(strengths) else ""
        w = f"- {sanitize_text(weaknesses[i])}" if i < len(weaknesses) else ""
        # Truncate for column layout
        pdf.cell(90, 6, s[:55] + ("..." if len(s) > 55 else ""), ln=0)
        pdf.cell(90, 6, w[:55] + ("..." if len(w) > 55 else ""), ln=1)
    
    pdf.ln(10)


    # --- PAGE 2: DETAIL SCORES ---
    pdf.add_page()
    pdf.set_font('DejaVu', 'B', 16)
    pdf.cell(0, 10, 'DETAIL SCORES', ln=1)
    pdf.ln(5)

    category_scores = result.get("category_scores", {})
    if not isinstance(category_scores, dict):
        category_scores = {}
        
    for cat, data in category_scores.items():
        if not isinstance(data, dict):
            data = {"score": 0, "explanation": str(data), "evidence": ""}
            
        score = data.get("score")
        if score is None:
            score_str = "N/A"
        else:
            score_str = f"{score}/10"

        pdf.set_font('DejaVu', 'B', 12)
        pdf.cell(0, 8, f"Category: {cat.replace('_', ' ').title()}", ln=1)
        
        pdf.set_font('DejaVu', '', 12)
        pdf.cell(0, 8, f"Score: {score_str}", ln=1)
        
        pdf.set_font('DejaVu', 'I', 10)
        explanation = sanitize_text(data.get('explanation', ''))
        evidence = sanitize_text(data.get('evidence', ''))
        pdf.multi_cell(0, 6, f"Explanation: {explanation}")
        pdf.multi_cell(0, 6, f'Evidence: "{evidence}"')
        pdf.ln(5)

    # --- PAGE 3: RECOMMENDATIONS ---
    pdf.add_page()
    pdf.set_font('DejaVu', 'B', 16)
    pdf.cell(0, 10, 'RECOMMENDATIONS', ln=1)
    pdf.ln(5)

    pdf.set_font('DejaVu', 'B', 12)
    pdf.cell(0, 8, 'Missing Sections:', ln=1)
    pdf.set_font('DejaVu', '', 10)
    
    missing = result.get("missing_sections", [])
    if not isinstance(missing, list):
        missing = []
    if not missing:
        pdf.cell(0, 6, "- None (All essential sections found)", ln=1)
    else:
        for m in missing:
            pdf.cell(0, 6, f"- {sanitize_text(m)}", ln=1)
            
    pdf.ln(5)

    pdf.set_font('DejaVu', 'B', 12)
    pdf.cell(0, 8, 'Improvement Suggestions:', ln=1)
    pdf.set_font('DejaVu', '', 10)
    suggs = result.get("improvement_suggestions", [])
    if not isinstance(suggs, list):
        suggs = []
    if not suggs:
        pdf.cell(0, 6, "- None", ln=1)
    else:
        for s in suggs:
            pdf.multi_cell(0, 6, f"- {sanitize_text(s)}")

    return pdf.output(dest='S')
